### ISSUE TITLE
Enable osd for FN buttons

### ISSUE THREAD

**Issue by StefosMarios** [sammilucia/ASUS-G14-Debloating#1] opened 2021-01-16 15:04 UTC
It's not an issue, but it might help you and others that followed this guide and removed MyAsus.

To enable OSD for FN buttons, set the following file:
`C:\Windows\System32\DriverStore\FileRepository\asussci2.inf_amd64_[UID]\ASUSOptimization\AsusOSD.exe`
To startup with windows (either add to startup apps or create a scheduled task)

P.S.1 Mic mute works fine for me.
P.S.2 I'm u/ebolaBoi from reddit ;)

**Comment by sammilucia** [comment] 2021-01-16 18:17
oh awesome, great work! I'll update the doc.

hi, nice to meet you again 😊😊

**Comment by sammilucia** [comment] 2021-01-24 21:40
Hmm, my mic button and OSD aren't working (I just have the regular Windows OSD) ... Did you do all the other steps in the tutorial?

**Comment by StefosMarios** [comment] 2021-01-25 21:14
I performed every step in your guide, except deleting stuff from ...\System32\DriverStore\FileRepository.
Mic mute is independant to the OSD startup and was always woking for me.
Try running the KB firmware update that's on Asus support page, this might solve your problem. Of course make sure you are on the latesst BIOS version.

I saw you had multple instances of the AsusOSD.exe. You can safely delete the
```C:\DRIVERS\*```
and
```C:\Ssupport\*```
if you want.

![image](https://user-images.githubusercontent.com/63734938/105763954-04ae5d80-5f5f-11eb-88fa-063dacd2f517.png)
The version that of the .exe that i used was inside the folder that has the latest "date modified"

Try double clicking it and testing if you osd works (for example try changing KB brightness).

For Reference, these are the files contained in the folder:
![image](https://user-images.githubusercontent.com/63734938/105766539-8eabf580-5f62-11eb-8cb3-b26251ea9045.png)

**Comment by sammilucia** [comment] 2021-01-26 00:29
hey - thank you so much!

huh, interesting! I've updated the keyboard firmware and BIOS but I didn't verify the newest versions took, so I'll go through the steps.

do you have any other ASUS*.exe, Armo*.exe or P50*.exe exes running?

thank you 😊

**Comment by StefosMarios** [comment] 2021-01-26 14:26
Only asus related .exe running are:

AsusOptimization.exe
AsusOptimizationStartupTask.exe
AsusOSD.exe

Also running the G14Control app (a proper armoury crate replacement if you ask me), but that has nothing to do with the functionalities we are discussing.
Just want to make the app as known as possible to our community ☺️

**Comment by sammilucia** [comment] 2021-01-26 18:27
Same... Curiouser and curiouser 😜

Yes same... I'd like all of this to be generally known. Once I've worked out the Fn bug on my system I'll update and repost to reddit.

Are you using the https://github.com/aredden/electron-g14control version?

**Comment by StefosMarios** [comment] 2021-01-26 18:33
Yeah. 
The dev is really active on discord.
If you know how to compile, pull the latest commit, i have pushed a bugfix and a "FN+F5 plan toggle" feature.
Otherwise wait for the next version (he's kinda busy ATM but hopefully he'll come around to it).

**Comment by sammilucia** [comment] 2021-01-26 18:43
okay that's awesome. I'm watching it on github so I should get notified. I couldn't install it before because my AV wouldn't whitelist it and it requires ring 0.

P.S. there's a new BIOS 219 I'd missed on ASUS (and a new ArmouryCrate).

(OT: I'm still undecided on running AV, I never have, but some of the latest malware is crazy. I've seen one use BitLocker the entire drive in the background, which means you can't get into safe mode or any other way to remove it because the drive's encrypted, and the W10 Settings fail to open so you can't retrieve the BitLocker hash or unencrypt the drive.)

**Comment by sammilucia** [comment] 2021-01-26 18:49
Just noting to myself the installall.bat script has `cd` bug when running from certain folders:
![sshot-2021-01-26-12-45-35](https://user-images.githubusercontent.com/3295286/105890354-dcf9dc80-5fd4-11eb-8c46-b8b68fad6b08.jpg)

Running from C:\ROG is okay. Won't affect all users because install.exe skips under [unknown] conditions.
![image](https://user-images.githubusercontent.com/3295286/105890454-00bd2280-5fd5-11eb-86b7-69316fcac85b.png)

**Comment by sammilucia** [comment] 2021-01-26 18:54
yay it's working. Thank you so much! i'll update the doco 😊

**Comment by StefosMarios** [comment] 2021-01-26 18:57
So, it's a ransomware that uses the built-in win mechanism 😅.
What if you have bit locker already enabled?

I'm not the right person to consult about security, only have the windows AV running. Then again, i also have UAC disabled so it doesn't bother me.

**Comment by StefosMarios** [comment] 2021-01-26 19:00
Nice!

Does mic muting also work or only the OSD?

**Comment by sammilucia** [comment] 2021-01-26 19:24
> What if you have bit locker already enabled?

yeah, I don't know how sophisticated the code is to cope with edge cases... and googling it, it seems like it's only been found in the wild a few times... it's probably obscure enough that many people just think it's a 'Windows killing itself' type problem.

the thing that worries me about it is, all the methods to remove it failed. I've never encountered malware I couldn't clean before... no AV would install... Malwarebytes wouldn't install, rkill wouldn't run etc., couldn't get into the Start Menu, Settings, or Safe Mode. this was trying to clean the PC remotely mind you, I may have had more success with hands-on access.

mind you, given how little info I could find on it, I'm not convinced any AV would have stopped it installing...

> I'm not the right person to consult about security

that's okay that's my background 😜

> Does mic muting also work or only the OSD?

yep, confirmed working without the OSD ... AsusOSD.exe is not needed if you're happy with the default Windows OSD 😊
![image](https://user-images.githubusercontent.com/3295286/105894229-a83c5400-5fd9-11eb-8bd8-9ca3a2ae551a.png)

**Comment by sammilucia** [comment] 2021-01-26 19:54
feel free to keep chatting, just closing issue because OCD 😜

**Closed as completed by sammilucia** 2021-01-26 19:54 UTC

**Comment by StefosMarios** [comment] 2021-01-26 20:00
Yeah OSD is totally optional but welcome when you want to make sure that mic is muted during a call 😅

Anyway, if i run into any other tips/suggestions, I'll let you know!

**Comment by sammilucia** [comment] 2021-01-26 20:08
The mic mute OSD is working without AsusOSD running! on W10 20H2 anyway...

**Comment by sammilucia** [comment] 2021-01-26 20:08
> Anyway, if i run into any other tips/suggestions, I'll let you know!

thanks! i've credited you on the new reddit post https://www.reddit.com/r/ZephyrusG14/comments/l5lsvq/asus_g14_remove_armoury_crate_myasus_and_asus/

**Comment by StefosMarios** [comment] 2021-01-26 20:10
> The mic mute OSD is working without AsusOSD running! on W10 20H2 anyway...

I know, talking about the notification (OSD) that mic is muted/unmuted.

**Comment by sammilucia** [comment] 2021-01-26 20:14
oh okay, I should probably run the OSD and see what I'm missing 😂

**Comment by StefosMarios** [comment] 2021-01-26 20:18
> > Anyway, if i run into any other tips/suggestions, I'll let you know!
> 
> thanks! i've credited you on the new reddit post https://www.reddit.com/r/ZephyrusG14/comments/l5lsvq/asus_g14_remove_armoury_crate_myasus_and_asus/

You don't have to credit me at all but for god's sake don't put the (throwaway) name ebolaBoi before yours and at the start of the post...
You made this informative GitHub, i just added a couple of tips.
We don't have nowhere near equal contribution

**Comment by sammilucia** [comment] 2021-02-01 02:34
oops, sorry! nobody read it anyway 😂
